// <auto-generated />
using CS174FINALPROJECTLITSCHER.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CS174FINALPROJECTLITSCHER.Migrations
{
    [DbContext(typeof(CS174FinalProjectLitscherContext))]
    [Migration("20201124200429_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CS174FINALPROJECTLITSCHER.Models.Appearance", b =>
                {
                    b.Property<string>("AppearanceID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AppearanceID");

                    b.ToTable("Appearances");

                    b.HasData(
                        new
                        {
                            AppearanceID = "all"
                        },
                        new
                        {
                            AppearanceID = "white"
                        },
                        new
                        {
                            AppearanceID = "orange"
                        });
                });

            modelBuilder.Entity("CS174FINALPROJECTLITSCHER.Models.Hardness", b =>
                {
                    b.Property<string>("HardnessID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Moisture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HardnessID");

                    b.ToTable("Hardnesses");

                    b.HasData(
                        new
                        {
                            HardnessID = "all",
                            Moisture = "All"
                        },
                        new
                        {
                            HardnessID = "soft",
                            Moisture = "Soft"
                        },
                        new
                        {
                            HardnessID = "semsoft",
                            Moisture = "Semi-soft"
                        },
                        new
                        {
                            HardnessID = "medhard",
                            Moisture = "Medium-hard"
                        },
                        new
                        {
                            HardnessID = "hard",
                            Moisture = "Semi-hard or hard"
                        });
                });

            modelBuilder.Entity("CS174FINALPROJECTLITSCHER.Models.Product", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AppearanceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HardnessID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImageFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productDesc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("productNominalWeight")
                        .HasColumnType("float");

                    b.Property<double>("productPrice")
                        .HasColumnType("float");

                    b.Property<int>("quantityOrdered")
                        .HasColumnType("int");

                    b.HasKey("productID");

                    b.HasIndex("AppearanceID");

                    b.HasIndex("HardnessID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            productID = 1,
                            AppearanceID = "white",
                            HardnessID = "soft",
                            ImageFile = "amsterdam.jpg",
                            productDesc = "Soft cow's-milk cheese. Pale in color with a slight grayish tinge",
                            productName = "Amsterdam",
                            productNominalWeight = 0.0,
                            productPrice = 25.0,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 2,
                            AppearanceID = "white",
                            HardnessID = "hard",
                            ImageFile = "bravo_cheddar.jpg",
                            productDesc = "Hard, off-white (or orange if colourings such as annatto are added), sometimes sharp-tasting, natural cheese",
                            productName = "Bravo Cheddar",
                            productNominalWeight = 0.0,
                            productPrice = 32.5,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 3,
                            AppearanceID = "orange",
                            HardnessID = "hard",
                            ImageFile = "cheddar.jpg",
                            productDesc = "Hard, off-white (or orange if colourings such as annatto are added), sometimes sharp-tasting, natural cheese",
                            productName = "Cheddar",
                            productNominalWeight = 0.0,
                            productPrice = 27.800000000000001,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 4,
                            AppearanceID = "white",
                            HardnessID = "semsoft",
                            ImageFile = "cheese_curds.jpg",
                            productDesc = "Same firmness and density as cheese, but with a springy or rubbery texture.[1] Fresh curds squeak against the teeth when bitten into",
                            productName = "Cheddar curds",
                            productNominalWeight = 0.0,
                            productPrice = 36.539999999999999,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 5,
                            AppearanceID = "orange",
                            HardnessID = "hard",
                            ImageFile = "Colby_Cheese.jpg",
                            productDesc = "Colby is softer, moister, and milder than cheddar because it is produced through a washed-curd process",
                            productName = "Colby",
                            productNominalWeight = 0.0,
                            productPrice = 21.5,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 6,
                            AppearanceID = "orange",
                            HardnessID = "hard",
                            ImageFile = "cheddar.jpg",
                            productDesc = "Commonly used as an interior melting cheese for California-style burritos, but also some Mexican-style burritos",
                            productName = "Monterey Jack",
                            productNominalWeight = 0.0,
                            productPrice = 37.799999999999997,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 7,
                            AppearanceID = "white",
                            HardnessID = "hard",
                            ImageFile = "keens-cheddar.jpg",
                            productDesc = "Tangy and rich our Extra Mature Unpasteurised Cheddar Cheese wakes up even the most drab of cheese boards.",
                            productName = "Keens Cheddar",
                            productNominalWeight = 0.0,
                            productPrice = 62.350000000000001,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 8,
                            AppearanceID = "white",
                            HardnessID = "soft",
                            ImageFile = "limburger_cheese.jpg",
                            productDesc = "The cheese is especially known for its strong smell caused by the bacterium Brevibacterium linens.",
                            productName = "Limburger",
                            productNominalWeight = 0.0,
                            productPrice = 16.98,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 9,
                            AppearanceID = "white",
                            HardnessID = "medhard",
                            ImageFile = "montforte_blue_cheese.jpg",
                            productDesc = "Vary in color through various shades of blue and green. This carries a distinct smell, either from that or various specially cultivated bacteria.",
                            productName = "Montforte Blue",
                            productNominalWeight = 0.0,
                            productPrice = 45.600000000000001,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 10,
                            AppearanceID = "white",
                            HardnessID = "medhard",
                            ImageFile = "Swiss_cheese.jpg",
                            productDesc = "Have a distinctive appearance, as the blocks or rounds of the cheese are riddled with holes known as eyes.",
                            productName = "Swiss",
                            productNominalWeight = 0.0,
                            productPrice = 60.450000000000003,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 11,
                            AppearanceID = "white",
                            HardnessID = "hard",
                            ImageFile = "200px-Grana_Padano_at_Eataly_in_Stockholm.jpg",
                            productDesc = "Hard, crumbly-textured cheese is made with unpasteurized cows' milk that is semi-skimmed through a natural creaming",
                            productName = "Grana Padano",
                            productNominalWeight = 0.0,
                            productPrice = 21.34,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 12,
                            AppearanceID = "white",
                            HardnessID = "soft",
                            ImageFile = "220px-Brie_01.jpg",
                            productDesc = "Soft cow's-milk cheese. Pale in color with a slight grayish tinge under a rind of white mould. ",
                            productName = "Brie",
                            productNominalWeight = 0.0,
                            productPrice = 34.210000000000001,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 13,
                            AppearanceID = "white",
                            HardnessID = "soft",
                            ImageFile = "220px-Cœurs_de_Neufchâtel_02.jpg",
                            productDesc = "soft, slightly crumbly, mold-ripened cheese made in the Neufchâtel-en-Bray, French region of Normandy.",
                            productName = "Neufchâtel",
                            productNominalWeight = 0.0,
                            productPrice = 62.149999999999999,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 14,
                            AppearanceID = "white",
                            HardnessID = "medhard",
                            ImageFile = "220px-Emmental_015.jpg",
                            productDesc = "Yellow, medium-hard Swiss cheese. It has a savory but mild taste.",
                            productName = "Emmental",
                            productNominalWeight = 0.0,
                            productPrice = 24.649999999999999,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 15,
                            AppearanceID = "white",
                            HardnessID = "medhard",
                            ImageFile = "220px-Gruyere_alpage_th_wa.jpg",
                            productDesc = "Sweet but slightly salty, with a flavor that varies widely with age. It is often described as creamy and nutty when young",
                            productName = "Gruyere",
                            productNominalWeight = 0.0,
                            productPrice = 34.869999999999997,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 16,
                            AppearanceID = "white",
                            HardnessID = "semsoft",
                            ImageFile = "220px-havarti.jpg",
                            productDesc = "Danish cow's milk cheese. It is a table cheese that can be sliced, grilled, or melted.[",
                            productName = "Havarti",
                            productNominalWeight = 0.0,
                            productPrice = 32.649999999999999,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 17,
                            AppearanceID = "white",
                            HardnessID = "medhard",
                            ImageFile = "220px-Jarlsberg_cheese.jpg",
                            productDesc = " It is a mild, buttery cheese. The flavor has been described as clean and rich, with a slightly sweet and nutty flavour.",
                            productName = "Jarlsberg",
                            productNominalWeight = 0.0,
                            productPrice = 19.190000000000001,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 18,
                            AppearanceID = "white",
                            HardnessID = "medhard",
                            ImageFile = "220px-Kaschkawal_Kashkaval_кашкавал_Balkankäse_Sofia_IMG_7649.jpg",
                            productDesc = "Type of blue cheese made of cow milk (kashkaval vitosha), sheep milk (kashkaval balkan), or both (kashkaval preslav)",
                            productName = "Kaschkawal",
                            productNominalWeight = 0.0,
                            productPrice = 20.199999999999999,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 19,
                            AppearanceID = "white",
                            HardnessID = "hard",
                            ImageFile = "220px-Parmigiano_Reggiano_meules_MIN_Rungis.jpg",
                            productDesc = "Parmigiano-Reggiano is commonly grated over pasta dishes, stirred into soups and risottos, and eaten on its own",
                            productName = "Parmigiano",
                            productNominalWeight = 0.0,
                            productPrice = 40.399999999999999,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 20,
                            AppearanceID = "white",
                            HardnessID = "semsoft",
                            ImageFile = "220px-Port_Salut_cheese.jpg",
                            productDesc = "Has a mild flavour. The smell increases the longer the cheese is kept",
                            productName = "Port_Salut",
                            productNominalWeight = 0.0,
                            productPrice = 32.450000000000003,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 21,
                            AppearanceID = "white",
                            HardnessID = "hard",
                            ImageFile = "220px-Somerset-Cheddar.jpg",
                            productDesc = "Hard, off-white (or orange if colourings such as annatto are added), sometimes sharp-tasting, natural cheese",
                            productName = "Somerset Cheddar",
                            productNominalWeight = 0.0,
                            productPrice = 23.449999999999999,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 22,
                            AppearanceID = "white",
                            HardnessID = "hard",
                            ImageFile = "220px-Sonoma_Jack_cheese_-_Stierch.jpg",
                            productDesc = "Commonly used as an interior melting cheese for California-style burritos, but also some Mexican-style burritos",
                            productName = "Sonoma Jack",
                            productNominalWeight = 0.0,
                            productPrice = 54.32,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 23,
                            AppearanceID = "orange",
                            HardnessID = "medhard",
                            ImageFile = "220px-WikiCheese_-_Gouda_36_mois_03.jpg",
                            productDesc = "Mild-flavored, yellow cow's milk cheese originating from the Netherlands. It is one of the most popular cheeses worldwide.",
                            productName = "Gouda",
                            productNominalWeight = 0.0,
                            productPrice = 43.210000000000001,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 24,
                            AppearanceID = "white",
                            HardnessID = "medhard",
                            ImageFile = "250px-Cantal_03.jpg",
                            productDesc = "Flavor is somewhat reminiscent of Cheddar, is a strong, tangy butter taste and grows with age. A well ripened Cantal has a vigorous taste",
                            productName = "Cantal",
                            productNominalWeight = 0.0,
                            productPrice = 12.34,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 25,
                            AppearanceID = "white",
                            HardnessID = "hard",
                            ImageFile = "250px-Cheshire_Cheese.jpg",
                            productDesc = "Dense and crumbly cheese produced in the English county of Cheshire, and four neighbouring counties",
                            productName = "Cheshire",
                            productNominalWeight = 0.0,
                            productPrice = 65.430000000000007,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 26,
                            AppearanceID = "orange",
                            HardnessID = "hard",
                            ImageFile = "250px-Colby_Cheese.jpg",
                            productDesc = "Colby is softer, moister, and milder than cheddar because it is produced through a washed-curd process",
                            productName = "Colby",
                            productNominalWeight = 0.0,
                            productPrice = 34.560000000000002,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 27,
                            AppearanceID = "white",
                            HardnessID = "hard",
                            ImageFile = "250px-Double_Gloucester_cheese.jpg",
                            productDesc = "Slab cheese, made in large creameries operated by major dairy companies such as Dairy Crest.",
                            productName = "Double Gloucester",
                            productNominalWeight = 0.0,
                            productPrice = 21.870000000000001,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 28,
                            AppearanceID = "white",
                            HardnessID = "semsoft",
                            ImageFile = "260px-Munster.jpg",
                            productDesc = "strong-smelling soft cheese with a subtle taste, made mainly from milk from the Vosges",
                            productName = "Munster",
                            productNominalWeight = 0.0,
                            productPrice = 32.979999999999997,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 29,
                            AppearanceID = "white",
                            HardnessID = "hard",
                            ImageFile = "260px-Pecorino_romano_on_board_cropped.png",
                            productDesc = "served with pears and walnuts or drizzled with strong chestnut honey.",
                            productName = "Pecorino Roman",
                            productNominalWeight = 0.0,
                            productPrice = 23.890000000000001,
                            quantityOrdered = 0
                        },
                        new
                        {
                            productID = 30,
                            AppearanceID = "white",
                            HardnessID = "medhard",
                            ImageFile = "260px-SmallEdamCheese.jpg",
                            productDesc = "Very mild flavour, slightly salty or nutty, and almost no smell when compared to other cheeses.As the cheese ages, its flavour sharpens, and it becomes firmer",
                            productName = "Small Edam",
                            productNominalWeight = 0.0,
                            productPrice = 21.449999999999999,
                            quantityOrdered = 0
                        });
                });

            modelBuilder.Entity("CS174FINALPROJECTLITSCHER.Models.Product", b =>
                {
                    b.HasOne("CS174FINALPROJECTLITSCHER.Models.Appearance", "Appearance")
                        .WithMany("Products")
                        .HasForeignKey("AppearanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CS174FINALPROJECTLITSCHER.Models.Hardness", "Hardness")
                        .WithMany("Products")
                        .HasForeignKey("HardnessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appearance");

                    b.Navigation("Hardness");
                });

            modelBuilder.Entity("CS174FINALPROJECTLITSCHER.Models.Appearance", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CS174FINALPROJECTLITSCHER.Models.Hardness", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
